-- 预录单
CREATE TABLE offer_order_import (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  delflag int NOT NULL COMMENT '0:初始 1:预录成功',
  userid int NOT NULL COMMENT '用户id',
  userrole int NOT NULL COMMENT '用户类型',
  paystatus int NOT NULL COMMENT '0:未支付 1:已支付',
  paymoney decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  downloadstatus int NOT NULL COMMENT '0:未下载 1:已下载',
  fileurl varchar(255) DEFAULT NULL comment '文件地址',


  membername varchar(50) DEFAULT NULL COMMENT '账号',
  username varchar(50) DEFAULT NULL COMMENT '姓名',
  boxinfo varchar(100) DEFAULT NULL COMMENT '箱信息',
  boxno varchar(50) NOT NULL COMMENT '箱号',
  shippname varchar(50) NOT NULL COMMENT '船名',
  shippno varchar(50) NOT NULL COMMENT '航次',
  imono varchar(50) NOT NULL COMMENT 'IMO编号',
  shipcall varchar(50) NOT NULL COMMENT '船舶呼号',
  inletwharf varchar(50) NOT NULL COMMENT '进箱码头',
  sizetype varchar(50) NOT NULL COMMENT '尺寸类型',
  smokebox varchar(50) NOT NULL COMMENT '箱皮重',
  statusinfo varchar(50) NOT NULL COMMENT '状态',
  boxoperator varchar(50) NOT NULL COMMENT '箱经营人',
  boxoperatorcode varchar(50) NOT NULL COMMENT '箱经营人代码',
  shippingdate datetime NOT NULL COMMENT '装箱日期',
  customscode varchar(50) NOT NULL COMMENT '海关代码',
  loadingport varchar(50) NOT NULL COMMENT '装港',
  loadingportcode varchar(50) NOT NULL COMMENT '装港代码',
  transitport varchar(50) NOT NULL COMMENT '卸港',
  transitportcode varchar(50) NOT NULL COMMENT '卸港代码',
  destport varchar(50) DEFAULT NULL COMMENT '目的港',
  destportcode varchar(50) DEFAULT NULL COMMENT '目的港代码',
  temperature varchar(50) NOT NULL COMMENT '冷藏温度',
  temperatureunit varchar(50) NOT NULL COMMENT '温度计量单位',
  temperaturemin varchar(50) NOT NULL COMMENT '冷藏最低温度',
  temperaturemax varchar(50) NOT NULL COMMENT '冷藏最高温度',
  dangerousgrade varchar(50) NOT NULL COMMENT '危险品等级',
  unnumber varchar(50) NOT NULL COMMENT '联合国编号',
  imdgpage varchar(50) DEFAULT NULL COMMENT '危规页码',
  flashpoint varchar(50) DEFAULT NULL COMMENT '闪点',
  dangerouslabel varchar(50) DEFAULT NULL COMMENT '危险品标签',
  emergencyno varchar(50) DEFAULT NULL COMMENT '应急措施号',
  firstaidno varchar(50) DEFAULT NULL COMMENT '急救指南号',
  marinepollution varchar(50) DEFAULT NULL COMMENT '海运污染',
  beforesuper varchar(50) DEFAULT NULL COMMENT '前超',
  aftersuper varchar(50) DEFAULT NULL COMMENT '后超',
  rightsuper varchar(50) DEFAULT NULL COMMENT '右超',
  leftsuper varchar(50) DEFAULT NULL COMMENT '左超',
  hignsuper varchar(50) DEFAULT NULL COMMENT '超高',
  shiptype varchar(50) DEFAULT NULL COMMENT '运输方式',
  passengerliner varchar(50) DEFAULT NULL COMMENT '班轮',
  shipnationcode varchar(50) DEFAULT NULL COMMENT '船舶国籍代码',
  impexpsign varchar(50) DEFAULT NULL COMMENT '进出口标志',
  packman varchar(50) DEFAULT NULL COMMENT '装箱人',
  packaddress varchar(50) DEFAULT NULL COMMENT '地址',
  licensenumber varchar(50) DEFAULT NULL COMMENT '车号',
  equipmentorder varchar(50) DEFAULT NULL COMMENT '设备交接单',
  detailaddress varchar(255) DEFAULT NULL COMMENT '装箱详细地址',
  remark varchar(255) DEFAULT NULL COMMENT '备注',
  callinfo varchar(50) NOT NULL COMMENT '封志信息(序号）',
  callno varchar(50) NOT NULL COMMENT '封志号',
  calltype varchar(50) NOT NULL COMMENT '封志类型',
  callman varchar(50) NOT NULL COMMENT '加封人',
  orderinfo varchar(50) NOT NULL COMMENT '提单信息(序号）',
  ordersn varchar(50) NOT NULL COMMENT '提单号',
  deliverycode varchar(50) NOT NULL COMMENT '交货地代码',
  deliveryport varchar(50) NOT NULL COMMENT '交货地',
  cargono varchar(50) NOT NULL COMMENT '货物序号',
  items varchar(50) NOT NULL COMMENT '件数',
  packagecode varchar(50) NOT NULL COMMENT '包装代码',
  packagetype varchar(50) NOT NULL COMMENT '包装类型',
  weight varchar(50) NOT NULL COMMENT '货重',
  size varchar(50) NOT NULL COMMENT '尺码',
  cargodesc varchar(255) NOT NULL COMMENT '货物描述',
  mark varchar(50) NOT NULL COMMENT '唛头',
  cargocode varchar(50) DEFAULT NULL COMMENT '货物代码',
  secdangerousgrade varchar(50) NOT NULL COMMENT '危险品等级',
  secunnumber varchar(50) NOT NULL COMMENT '联合国编号',
  secimdgpage varchar(50) DEFAULT NULL COMMENT '危险品页号',
  secflashpoint varchar(50) DEFAULT NULL COMMENT '闪点',
  secdangerouslabel varchar(50) DEFAULT NULL COMMENT '危险品标签',
  secemergencyno varchar(50) DEFAULT NULL COMMENT '应急措施号',
  secfirstaidno varchar(50) DEFAULT NULL COMMENT '急救指南号',
  secmarinepollution varchar(50) DEFAULT NULL COMMENT '海运污染',



  create_time datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
